import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import { ConfigProvider } from 'antd';
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from '@/widgets/Header/Header';
import Sidebar from '@/widgets/Sidebar/Sidebar';

const theme = {
  token: {
    colorPrimary: "#1890ff", 
    colorBgBase: "#ffffff",
    colorTextBase: "#1f1f1f",
    colorBorder: "#d9d9d9",
    borderRadius: 8,
    fontFamily: "var(--font-geist-sans)",
  },
  components: {
    Button: {
      colorPrimaryHover: "#40a9ff",
      colorPrimaryActive: "#096dd9",
    },
    Radio: {
      colorPrimary: "#1890ff",
    },
    Select: {
      colorPrimary: "#1890ff",
      colorBgContainer: "#fff",
      controlOutline: "none",
    },
  },
};

const geistSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <div className="page page--configurator">
              <Header />
              <Sidebar />
              {children}
            </div>

          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
